# Generated by Django 3.2.13 on 2022-10-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='person',
            new_name='user',
        ),
    ]
