# Generated by Django 3.2.13 on 2022-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
