# Generated by Django 3.2.13 on 2022-10-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='running_time',
        ),
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='part',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
