# Generated by Django 3.2.13 on 2022-10-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20221006_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='active',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='part',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='weight',
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
